version: "3.4"

networks:
  db_net:
    external: true
  default:

services:
  core: &service
    container_name: helper
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/src
    networks:
      - default
    restart: unless-stopped
